baseURL = "https://garcias.github.io/reducing-stereotype-threat"
languageCode = "en-us"
title = "Reducing Stereotype Threat Archive"
theme = "hyde-hyde"
toc = true
sectionPagesMenu = "main"
relativeURLs = true
pluralizelisttitles = false
publishDir = "docs"
[params]
    themeColor = "theme-base-0d"
    layoutReverse = false
